import { CardDef, ClanId, LocationDef, AllyCard } from '@kindred/shared';

// ─── 地點定義 ────────────────────────────────

// 全部地點（依序：#1、#2、#3、王子的避難所）
// 3–4 人使用前 3 個；5–6 人使用全部 4 個
export const LOCATIONS: LocationDef[] = [
  {
    id: 'rack',
    name: 'The Rack',
    influence: [[1, 0], [1, 1], [2, 1]],
    isPrinces: false,
  },
  {
    id: 'asylum',
    name: 'The Asylum',
    influence: [[1, 0], [1, 1], [2, 1]],
    isPrinces: false,
  },
  {
    id: 'club_zombie',
    name: 'Club Zombie',
    influence: [[1, 0], [1, 1], [2, 1]],
    isPrinces: false,
  },
  {
    id: 'haven',
    name: "Prince's Haven",
    influence: [[2, 0], [2, 1], [3, 1]],
    isPrinces: true,
  },
];

// ─── 氏族定義 ────────────────────────────────

export const CLAN_DEFS: Record<ClanId, {
  name: string;
  name_zh: string;
  color: string;
  archetype_zh: string;
  startBlood: number;
  startInfluence: number;
}> = {
  brujah: {
    name: 'Brujah',
    name_zh: '布魯哈',
    color: '#8b0000',
    archetype_zh: '全攻快攻',
    startBlood: 6,
    startInfluence: 3,
  },
  nosferatu: {
    name: 'Nosferatu',
    name_zh: '諾斯費拉圖',
    color: '#1a3d1a',
    archetype_zh: '情報控制',
    startBlood: 6,
    startInfluence: 3,
  },
  toreador: {
    name: 'Toreador',
    name_zh: '托雷亞多爾',
    color: '#0d5050',
    archetype_zh: '同盟操控',
    startBlood: 6,
    startInfluence: 3,
  },
  tremere: {
    name: 'Tremere',
    name_zh: '特雷梅爾',
    color: '#3d0060',
    archetype_zh: '血液魔法爆發',
    startBlood: 6,
    startInfluence: 3,
  },
  malkavian: {
    name: 'Malkavian',
    name_zh: '馬爾卡維安',
    color: '#6b0040',
    archetype_zh: '混亂干擾',
    startBlood: 6,
    startInfluence: 3,
  },
  gangrel: {
    name: 'Gangrel',
    name_zh: '剛格烈',
    color: '#5a4000',
    archetype_zh: '血液操控耐久',
    startBlood: 6,
    startInfluence: 3,
  },
  ventrue: {
    name: 'Ventrue',
    name_zh: '凡崔',
    color: '#0a2050',
    archetype_zh: '棋盤控制',
    startBlood: 6,
    startInfluence: 3,
  },
};

// ─── 布魯哈牌組 ──────────────────────────────

const BRUJAH_CARDS: CardDef[] = [
  {
    id: 'BR09',
    name_en: 'Hunt',
    name_zh: '狩獵',
    clan: 'brujah',
    type: 'aftermath',
    power: 0,
    effect_en: 'Steal 1 blood from each Rival.',
    effect_zh: '從每個對手各偷取 1 點血液。',
    is_starter: true,
  },
  {
    id: 'BR08',
    name_en: 'Ready',
    name_zh: '備戰',
    clan: 'brujah',
    type: 'passive',
    power: 1,
    effect_en: 'If you send a Rival into Frenzy, you gain an additional +1 Influence.',
    effect_zh: '若你使一個對手進入狂暴，你額外獲得 +1 影響力。',
    is_starter: true,
  },
  {
    id: 'BR01',
    name_en: 'Bloody Fury',
    name_zh: '血腥狂怒',
    clan: 'brujah',
    type: 'conflict',
    power: 6,
    effect_en: 'If you have any Deployed blood at this Location, this card gets -2 Power.',
    effect_zh: '若你在此地點有任何部署血液，此牌的權力值 -2。',
    is_starter: false,
  },
  {
    id: 'BR02',
    name_en: "Punk's Posse",
    name_zh: '龐克幫眾',
    clan: 'brujah',
    type: 'conflict',
    power: 0,
    effect_en: 'This card gets +2 Power for each of your Deployed cards at this Location, including this one.',
    effect_zh: '此牌獲得 +2 權力值，等同你在此地點的每張部署牌數量（包含此牌本身）。',
    is_starter: false,
  },
  {
    id: 'BR03',
    name_en: 'Challenge',
    name_zh: '挑戰宣言',
    clan: 'brujah',
    type: 'passive',
    power: 4,
    effect_en: 'Whenever an opponent plays a card at a different Location than this card, they Lose 1 blood.',
    effect_zh: '每當對手在與此牌不同的地點出牌時，該對手失去 1 點血液。',
    is_starter: false,
  },
  {
    id: 'BR04',
    name_en: 'Fist of Caine',
    name_zh: '該隱之拳',
    clan: 'brujah',
    type: 'aftermath',
    power: 4,
    effect_en: 'Each Rival Loses: 1 blood in the 1st Round, 2 blood in the 2nd Round, 3 blood in the 3rd Round.',
    effect_zh: '每個對手失去血液：第 1 回合 1 點，第 2 回合 2 點，第 3 回合 3 點。',
    is_starter: false,
  },
  {
    id: 'BR05',
    name_en: 'F*ck the System',
    name_zh: '打倒體制',
    clan: 'brujah',
    type: 'aftermath',
    power: 3,
    effect_en: 'If you win at this Location, each Rival Loses 4 blood. If you don\'t, they Lose 2 blood.',
    effect_zh: '若你贏得此地點，每個對手失去 4 點血液；若你未贏，他們失去 2 點血液。',
    is_starter: false,
  },
  {
    id: 'BR06',
    name_en: 'Earthshock',
    name_zh: '地震衝擊',
    clan: 'brujah',
    type: 'aftermath',
    power: 2,
    effect_en: 'Add up the total Deployed blood at this Location for all players. Each Rival Loses 1 blood for every 2 blood in this sum.',
    effect_zh: '計算此地點所有玩家的部署血液總量，每 2 點血液使每個對手失去 1 點血液。',
    is_starter: false,
  },
  {
    id: 'BR07',
    name_en: 'Show of Force',
    name_zh: '展示武力',
    clan: 'brujah',
    type: 'preparation',
    power: 3,
    effect_en: 'Steal 1 blood from each Rival.',
    effect_zh: '從每個對手各偷取 1 點血液。',
    is_starter: false,
  },
];

// ─── 諾斯費拉圖牌組 ──────────────────────────

const NOSFERATU_CARDS: CardDef[] = [
  {
    id: 'NO09',
    name_en: 'Hunt',
    name_zh: '狩獵',
    clan: 'nosferatu',
    type: 'aftermath',
    power: 0,
    effect_en: "Steal 1 blood from each Rival, then you may move this card to the Prince's Haven.",
    effect_zh: '從每個對手各偷取 1 點血液，然後你可以將此牌移至王子的避難所。',
    is_starter: true,
  },
  {
    id: 'NO08',
    name_en: 'Ready',
    name_zh: '備戰',
    clan: 'nosferatu',
    type: 'passive',
    power: 1,
    effect_en: "This card gets +2 Power when it is Deployed at the Prince's Haven.",
    effect_zh: '當此牌部署在王子的避難所時，獲得 +2 權力值。',
    is_starter: true,
  },
  {
    id: 'NO01',
    name_en: 'Unseen Passage',
    name_zh: '隱形通道',
    clan: 'nosferatu',
    type: 'aftermath',
    power: 2,
    effect_en: "Move this card to the Prince's Haven.",
    effect_zh: '將此牌移至王子的避難所。',
    is_starter: false,
  },
  {
    id: 'NO02',
    name_en: 'Cloak of Shadows',
    name_zh: '陰影斗篷',
    clan: 'nosferatu',
    type: 'passive',
    power: 3,
    effect_en: 'Whenever you Withdraw from any other Location, instead of following the regular rules, you may choose to take your Deployed cards and blood from there and move them to this Location.',
    effect_zh: '每當你從其他地點撤退時，你可以不遵照常規規則，改為將你在那裡的部署牌和血液移至此地點。',
    is_starter: false,
  },
  {
    id: 'NO03',
    name_en: 'Eyes in the Dark',
    name_zh: '暗中之眼',
    clan: 'nosferatu',
    type: 'passive',
    power: 2,
    effect_en: 'During the Planning phase, when playing cards at this Location, your opponents must Spend blood and play them face down. You can look at all these cards at any time. Whenever a card is played face down here, take 1 blood from the Bank and play it at this Location.',
    effect_zh: '在規劃階段，對手在此地點出牌時，必須消耗血液且面朝下出牌。你可以隨時查看這些牌。每當一張牌在此地點面朝下出牌時，從銀行取 1 點血液部署至此地點。',
    is_starter: false,
  },
  {
    id: 'NO04',
    name_en: 'Feral Whispers',
    name_zh: '野性耳語',
    clan: 'nosferatu',
    type: 'passive',
    power: 1,
    effect_en: 'When you Withdraw from any other Location, take 2 blood from the Bank for each card you moved and play them at this Location.',
    effect_zh: '當你從任何其他地點撤退時，從銀行取 2 點血液（每張移走的牌各取 2 點），部署至此地點。',
    is_starter: false,
  },
  {
    id: 'NO05',
    name_en: 'Backstab',
    name_zh: '背刺',
    clan: 'nosferatu',
    type: 'preparation',
    power: 2,
    effect_en: "Play up to 3 blood at this Location. Then, you may move this card to the Prince's Haven.",
    effect_zh: '在此地點部署最多 3 點血液，然後你可以將此牌移至王子的避難所。',
    is_starter: false,
  },
  {
    id: 'NO06',
    name_en: 'One Step Ahead',
    name_zh: '領先一步',
    clan: 'nosferatu',
    type: 'passive',
    power: 3,
    effect_en: 'During Revelation, for each face down Deployed card they have at this Location, each Rival must choose to either Lose 2 blood to flip it face up or leave it face down.',
    effect_zh: '揭牌時，此地點每張對手面朝下的部署牌，每個對手必須選擇：失去 2 點血液將其翻面，或讓它保持面朝下。',
    is_starter: false,
  },
  {
    id: 'NO07',
    name_en: 'Vanish',
    name_zh: '消失於影',
    clan: 'nosferatu',
    type: 'preparation',
    power: 4,
    effect_en: 'You may choose to Withdraw. If you do, Steal 1 blood from each Rival.',
    effect_zh: '你可以選擇撤退。若如此，從每個對手各偷取 1 點血液。',
    is_starter: false,
  },
];

// ─── 托雷亞多爾牌組 ──────────────────────────

const TOREADOR_CARDS: CardDef[] = [
  {
    id: 'TO09',
    name_en: 'Hunt',
    name_zh: '狩獵',
    clan: 'toreador',
    type: 'aftermath',
    power: 0,
    effect_en: 'Steal 1 blood from each Rival.',
    effect_zh: '從每個對手各偷取 1 點血液。',
    is_starter: true,
  },
  {
    id: 'TO08',
    name_en: 'Ready',
    name_zh: '備戰',
    clan: 'toreador',
    type: 'preparation',
    power: 0,
    effect_en: 'Draw a Victim from the deck and add it to your Alliance.',
    effect_zh: '從牌堆抽取一張受害者牌，加入你的同盟。',
    is_starter: true,
  },
  {
    id: 'TO01',
    name_en: 'Awe',
    name_zh: '敬畏',
    clan: 'toreador',
    type: 'aftermath',
    power: 2,
    effect_en: 'Steal 1 blood from each Rival for every 2 cards in your Alliance.',
    effect_zh: '你同盟中每 2 張牌，從每個對手各偷取 1 點血液。',
    is_starter: false,
  },
  {
    id: 'TO02',
    name_en: 'Entourage',
    name_zh: '隨從群',
    clan: 'toreador',
    type: 'conflict',
    power: 0,
    effect_en: 'This card gets +1 Power for each card in your Alliance (up to +7 max).',
    effect_zh: '此牌獲得 +1 權力值，等同你同盟中的牌數（最多 +7）。',
    is_starter: false,
  },
  {
    id: 'TO03',
    name_en: 'Charisma',
    name_zh: '魅力',
    clan: 'toreador',
    type: 'preparation',
    power: 2,
    effect_en: 'Each Rival must Discard 1 Deployed blood from this Location for every 2 cards in your Alliance.',
    effect_zh: '每個對手必須從此地點棄置部署血液，你同盟中每 2 張牌迫使每位對手棄置 1 點。',
    is_starter: false,
  },
  {
    id: 'TO04',
    name_en: 'Summon',
    name_zh: '召喚',
    clan: 'toreador',
    type: 'aftermath',
    power: 3,
    effect_en: 'If you win an Ally or a Victim after the Conflict at this Location, draw an additional Victim from the deck and add it to your Alliance.',
    effect_zh: '若你在此地點衝突後贏得一張盟友牌或受害者牌，再從牌堆額外抽一張受害者牌加入你的同盟。',
    is_starter: false,
  },
  {
    id: 'TO05',
    name_en: 'Entrancement',
    name_zh: '魅惑',
    clan: 'toreador',
    type: 'conflict',
    power: 0,
    effect_en: "This card gets +1 Power for each Deployed card at this Location (at your Position and all Rivals').",
    effect_zh: '此牌獲得 +1 權力值，等同此地點所有位置的部署牌數量（包含你的位置和所有對手的位置）。',
    is_starter: false,
  },
  {
    id: 'TO06',
    name_en: 'Submission',
    name_zh: '臣服',
    clan: 'toreador',
    type: 'passive',
    power: 3,
    effect_en: 'You are immune to Lose blood and/or Steal blood effects triggered at this Location. If Losing blood was a condition to trigger an effect, it counts as if you lost it.',
    effect_zh: '你免疫此地點觸發的失去血液和偷取血液效果。若失去血液是觸發效果的條件，視為你已失去。',
    is_starter: false,
  },
  {
    id: 'TO07',
    name_en: 'Friends in High Places',
    name_zh: '高層人脈',
    clan: 'toreador',
    type: 'passive',
    power: 3,
    effect_en: 'Before Revelation, you may play 1 blood at this Location for each card in your Alliance.',
    effect_zh: '揭牌前，你可以為你同盟中的每張牌在此地點部署 1 點血液。',
    is_starter: false,
  },
];

// ─── 特雷梅爾牌組 ────────────────────────────

const TREMERE_CARDS: CardDef[] = [
  {
    id: 'TR09',
    name_en: 'Hunt',
    name_zh: '狩獵',
    clan: 'tremere',
    type: 'aftermath',
    power: 1,
    effect_en: 'You may Spend 1 blood to Steal 1 blood from each Rival.',
    effect_zh: '你可以消耗 1 點血液，從每個對手各偷取 1 點血液。',
    is_starter: true,
  },
  {
    id: 'TR08',
    name_en: 'Ready',
    name_zh: '備戰',
    clan: 'tremere',
    type: 'conflict',
    power: 1,
    effect_en: 'If you enter Frenzy at this Location, you may flip this card face down instead of Draining a card from your Alliance. If you do, Gain 1 blood from the Bank.',
    effect_zh: '若你在此地點進入狂暴，你可以將此牌翻至面朝下，代替從同盟汲取牌。若如此，從銀行獲得 1 點血液。',
    is_starter: true,
  },
  {
    id: 'TR01',
    name_en: 'Focus from Hunger',
    name_zh: '飢餓中的專注',
    clan: 'tremere',
    type: 'conflict',
    power: 9,
    effect_en: 'This card gets -1 Power for each blood you have in your Pool.',
    effect_zh: '此牌的權力值 -1，等同你資源池中的每點血液數。',
    is_starter: false,
  },
  {
    id: 'TR02',
    name_en: 'Ancient Artifacts',
    name_zh: '古老文物',
    clan: 'tremere',
    type: 'preparation',
    power: 6,
    effect_en: 'You must Spend half of the blood from your Pool (rounded down) or flip this card face down.',
    effect_zh: '你必須消耗資源池中一半的血液（向下取整），否則將此牌翻至面朝下。',
    is_starter: false,
  },
  {
    id: 'TR03',
    name_en: 'Theft of Vitae',
    name_zh: '竊取生命力',
    clan: 'tremere',
    type: 'preparation',
    power: 3,
    effect_en: 'Gain blood until you have 7 blood in your Pool. If you already have 7 or more blood in your Pool, Gain 1 blood instead.',
    effect_zh: '獲得血液直到你的資源池達 7 點。若你的資源池已有 7 點或以上，改為獲得 1 點血液。',
    is_starter: false,
  },
  {
    id: 'TR04',
    name_en: 'Dark Pact',
    name_zh: '黑暗契約',
    clan: 'tremere',
    type: 'passive',
    power: 1,
    effect_en: 'Whenever you Lose blood or Spend blood at any Location, play it on this Location instead of discarding it to the Bank.',
    effect_zh: '每當你在任何地點失去血液或消耗血液時，將該血液部署至此地點，而非歸還銀行。',
    is_starter: false,
  },
  {
    id: 'TR05',
    name_en: 'Cauldron of Blood',
    name_zh: '血液坩堝',
    clan: 'tremere',
    type: 'aftermath',
    power: 3,
    effect_en: 'You may Spend half of the blood from your Pool (rounded down); If you do, each Rival Loses 4 blood.',
    effect_zh: '你可以消耗資源池中一半的血液（向下取整）；若如此，每個對手失去 4 點血液。',
    is_starter: false,
  },
  {
    id: 'TR06',
    name_en: 'Retaliation',
    name_zh: '反制報復',
    clan: 'tremere',
    type: 'passive',
    power: 2,
    effect_en: 'At this Location, whenever you Spend blood or you are the target of a Lose blood or Steal blood effect, each Rival Loses an equal amount of blood.',
    effect_zh: '在此地點，每當你消耗血液或成為失去血液／偷取血液效果的目標時，每個對手失去等量的血液。',
    is_starter: false,
  },
  {
    id: 'TR07',
    name_en: 'Arcane Drain',
    name_zh: '奧術汲取',
    clan: 'tremere',
    type: 'preparation',
    power: 2,
    effect_en: "You may Spend half of the blood from your Pool (rounded down); if you do, take half of each Rival's Deployed blood at this Location (rounded up) and add it to your Pool.",
    effect_zh: '你可以消耗資源池中一半的血液（向下取整）；若如此，取走每個對手在此地點部署血液的一半（向上取整），加入你的資源池。',
    is_starter: false,
  },
];

// ─── 馬爾卡維安牌組 ──────────────────────────

const MALKAVIAN_CARDS: CardDef[] = [
  {
    id: 'MA09',
    name_en: 'Hunt',
    name_zh: '狩獵',
    clan: 'malkavian',
    type: 'aftermath',
    power: 0,
    effect_en: 'Steal 1 blood from each Rival.',
    effect_zh: '從每個對手各偷取 1 點血液。',
    is_starter: true,
  },
  {
    id: 'MA08',
    name_en: 'Ready',
    name_zh: '備戰',
    clan: 'malkavian',
    type: 'conflict',
    power: 0,
    effect_en: 'This card gets +1 Power for each of your Deployed cards at this Location, including this one.',
    effect_zh: '此牌獲得 +1 權力值，等同你在此地點的每張部署牌數量（包含此牌本身）。',
    is_starter: true,
  },
  {
    id: 'MA01',
    name_en: 'Mesmerize',
    name_zh: '催眠操控',
    clan: 'malkavian',
    type: 'preparation',
    power: 3,
    effect_en: 'Choose a Rival. Play all of the cards remaining in their hand on your Position at this Location, face up.',
    effect_zh: '選擇一個對手，將他們手中剩餘的所有牌面朝上部署至你在此地點的位置。',
    is_starter: false,
  },
  {
    id: 'MA02',
    name_en: 'Auction of Blood',
    name_zh: '血液拍賣',
    clan: 'malkavian',
    type: 'passive',
    power: 2,
    effect_en: 'Immediately after Revelation, you and all Rivals must secretly bid with blood from your Pools. The lowest bidder must flip one of their Deployed cards at this Location face down. Then, play any blood you bid at this Location; your Rivals Lose their bids.',
    effect_zh: '揭牌後立即，你和所有對手必須秘密以血液出價。出價最低者必須將他們在此地點的一張部署牌翻至面朝下。然後，你出價的血液部署至此地點；你的對手失去他們的出價。',
    is_starter: false,
  },
  {
    id: 'MA03',
    name_en: 'Madness Network',
    name_zh: '瘋狂網絡',
    clan: 'malkavian',
    type: 'preparation',
    power: 2,
    effect_en: 'Play all of the cards remaining in your hand at this Location, face up.',
    effect_zh: '將你手中剩餘的所有牌面朝上部署至此地點。',
    is_starter: false,
  },
  {
    id: 'MA04',
    name_en: 'Shadow Strike',
    name_zh: '暗影突襲',
    clan: 'malkavian',
    type: 'conflict',
    power: 3,
    effect_en: 'If you have the lowest number of face up Deployed cards at this Location (even if you are tied), this card gets +2 Power.',
    effect_zh: '若你在此地點面朝上的部署牌數量最少（即使平手），此牌獲得 +2 權力值。',
    is_starter: false,
  },
  {
    id: 'MA05',
    name_en: 'Chaos',
    name_zh: '混沌',
    clan: 'malkavian',
    type: 'preparation',
    power: 2,
    effect_en: 'You may choose to take 1 or more Deployed cards from your position at this Location back into your hand, including this one. For each card you take back, Steal 1 blood from each Rival.',
    effect_zh: '你可以選擇將你在此地點的 1 張或多張部署牌（包含此牌）收回手中。每收回一張牌，從每個對手各偷取 1 點血液。',
    is_starter: false,
  },
  {
    id: 'MA06',
    name_en: "Malkav's Bane",
    name_zh: '馬爾卡夫之禍',
    clan: 'malkavian',
    type: 'passive',
    power: 2,
    effect_en: 'Immediately after Revelation, draw the top card from your Clan deck and play it at this Location. At the End of the Round, when you take back your clan cards shuffle 1 card of your choice from your hand back into your deck.',
    effect_zh: '揭牌後立即，從你的氏族牌堆頂端抽一張牌並部署至此地點。回合結束取回氏族牌時，從手中洗回 1 張你選擇的牌至牌堆。',
    is_starter: false,
  },
  {
    id: 'MA07',
    name_en: 'Mindless Assault',
    name_zh: '無腦衝擊',
    clan: 'malkavian',
    type: 'preparation',
    power: 3,
    effect_en: 'You may choose to flip 1 or more Deployed cards on your position at this Location face down; each face down Deployed card on your Position at this Location has 4 Power.',
    effect_zh: '你可以選擇將你在此地點位置上的 1 張或多張部署牌翻至面朝下；你在此地點位置上的每張面朝下部署牌的權力值為 4。',
    is_starter: false,
  },
];

// ─── 剛格烈牌組 ──────────────────────────────

const GANGREL_CARDS: CardDef[] = [
  {
    id: 'GA09',
    name_en: 'Hunt',
    name_zh: '狩獵',
    clan: 'gangrel',
    type: 'aftermath',
    power: 0,
    effect_en: 'Steal 1 blood from each Rival.',
    effect_zh: '從每個對手各偷取 1 點血液。',
    is_starter: true,
  },
  {
    id: 'GA08',
    name_en: 'Ready',
    name_zh: '備戰',
    clan: 'gangrel',
    type: 'preparation',
    power: 0,
    effect_en: 'Take 2 blood from the Bank and play them at this Location.',
    effect_zh: '從銀行取 2 點血液，部署至此地點。',
    is_starter: true,
  },
  {
    id: 'GA01',
    name_en: 'Earth Meld',
    name_zh: '融入大地',
    clan: 'gangrel',
    type: 'aftermath',
    power: 1,
    effect_en: 'Move all your Deployed blood from this Location back into your Pool.',
    effect_zh: '將你在此地點所有部署血液移回你的資源池。',
    is_starter: false,
  },
  {
    id: 'GA02',
    name_en: 'Wolf Companion',
    name_zh: '狼族夥伴',
    clan: 'gangrel',
    type: 'conflict',
    power: 2,
    effect_en: "The printed Power value on each of your Rivals' Deployed cards at this Location is halved (rounded down).",
    effect_zh: '此地點每個對手的部署牌的印刷權力值減半（向下取整）。',
    is_starter: false,
  },
  {
    id: 'GA03',
    name_en: 'Feral Weapons',
    name_zh: '野性武器',
    clan: 'gangrel',
    type: 'conflict',
    power: 1,
    effect_en: 'Each Deployed blood you have at this Location adds 2 Power (instead of 1).',
    effect_zh: '你在此地點的每點部署血液提供 2 點權力值（而非 1 點）。',
    is_starter: false,
  },
  {
    id: 'GA04',
    name_en: 'Power of the Pack',
    name_zh: '狼群之力',
    clan: 'gangrel',
    type: 'preparation',
    power: 2,
    effect_en: 'Take half of the Deployed blood from each Rival at this Location (rounded up) and add it to your Pool.',
    effect_zh: '從每個對手在此地點的部署血液中取走一半（向上取整），加入你的資源池。',
    is_starter: false,
  },
  {
    id: 'GA05',
    name_en: 'Fearless',
    name_zh: '無懼',
    clan: 'gangrel',
    type: 'preparation',
    power: 3,
    effect_en: 'You may choose to swap your Deployed blood from this Location with the blood in your Pool. If you do, take 2 blood from the Bank and play them here.',
    effect_zh: '你可以選擇將你在此地點的部署血液與資源池中的血液互換。若如此，從銀行額外取 2 點血液部署至此地點。',
    is_starter: false,
  },
  {
    id: 'GA06',
    name_en: 'On the Prowl',
    name_zh: '徘徊狩獵',
    clan: 'gangrel',
    type: 'passive',
    power: 3,
    effect_en: 'Whenever an opponent plays a card at this Location, take 1 blood from the Bank and play it here.',
    effect_zh: '每當對手在此地點出牌時，從銀行取 1 點血液並部署至此地點。',
    is_starter: false,
  },
  {
    id: 'GA07',
    name_en: 'Mist Form',
    name_zh: '迷霧型態',
    clan: 'gangrel',
    type: 'aftermath',
    power: 2,
    effect_en: 'You may move half of your Deployed blood from this Location (rounded up) to any other Location.',
    effect_zh: '你可以將此地點部署血液的一半（向上取整）移至任意其他地點。',
    is_starter: false,
  },
];

// ─── 凡崔牌組 ────────────────────────────────

const VENTRUE_CARDS: CardDef[] = [
  {
    id: 'VE09',
    name_en: 'Hunt',
    name_zh: '狩獵',
    clan: 'ventrue',
    type: 'aftermath',
    power: 0,
    effect_en: 'The winner of this Location must either let you Steal 2 blood from them or give you 1 Influence.',
    effect_zh: '此地點的勝者必須選擇：讓你從他們那裡偷取 2 點血液，或給予你 1 點影響力。',
    is_starter: true,
  },
  {
    id: 'VE08',
    name_en: 'Ready',
    name_zh: '備戰',
    clan: 'ventrue',
    type: 'conflict',
    power: 2,
    effect_en: null,
    effect_zh: null,
    is_starter: true,
  },
  {
    id: 'VE01',
    name_en: 'Master Plan',
    name_zh: '主謀計劃',
    clan: 'ventrue',
    type: 'passive',
    power: 3,
    effect_en: 'At the end of the Planning Phase, each opponent with no Deployed cards here Loses 1 Influence. This card gets +1 Power for each Rival at this Location.',
    effect_zh: '規劃階段結束時，每個在此地點沒有部署牌的對手失去 1 點影響力。此牌獲得 +1 權力值，等同此地點的對手數。',
    is_starter: false,
  },
  {
    id: 'VE02',
    name_en: 'Diplomacy',
    name_zh: '外交手腕',
    clan: 'ventrue',
    type: 'conflict',
    power: 3,
    effect_en: 'Before applying any other effect, the Deployed card with the highest printed Power at this Location (ignoring those at your Position) has its Power reduced to 0. In case of a tie, all tied cards are affected.',
    effect_zh: '在套用任何其他效果之前，此地點印刷權力值最高的部署牌（忽略你位置上的）的權力值降至 0。若有平手，所有平手的牌均受影響。',
    is_starter: false,
  },
  {
    id: 'VE03',
    name_en: 'Curfew',
    name_zh: '宵禁令',
    clan: 'ventrue',
    type: 'conflict',
    power: 2,
    effect_en: 'Immediately after Revelation, each of your Rivals must choose to either skip the Preparation and Aftermath Steps or let you Steal 3 blood from them.',
    effect_zh: '揭牌後立即，你的每個對手必須選擇：跳過準備和後果步驟，或讓你從他們那裡偷取 3 點血液。',
    is_starter: false,
  },
  {
    id: 'VE04',
    name_en: 'Majesty',
    name_zh: '威嚴',
    clan: 'ventrue',
    type: 'conflict',
    power: 0,
    effect_en: 'The Power of this card is equal to the highest printed Power value on a Deployed card at this Location.',
    effect_zh: '此牌的權力值等同此地點印刷權力值最高的部署牌。',
    is_starter: false,
  },
  {
    id: 'VE05',
    name_en: 'Mass Manipulation',
    name_zh: '大規模操控',
    clan: 'ventrue',
    type: 'passive',
    power: 3,
    effect_en: 'During the Withdraw Step at this Location, each Rival must either Withdraw or let you Steal 2 blood from them to Stay.',
    effect_zh: '在此地點的撤退步驟中，每個對手必須選擇撤退，或讓你從他們那裡偷取 2 點血液才能留守。',
    is_starter: false,
  },
  {
    id: 'VE06',
    name_en: "Tyrant's Gaze",
    name_zh: '暴君凝視',
    clan: 'ventrue',
    type: 'preparation',
    power: 2,
    effect_en: 'Each Rival must either move half of the Deployed blood they have at this Location (rounded up) to your Position, or Lose 1 Influence.',
    effect_zh: '每個對手必須選擇：將他們在此地點部署血液的一半（向上取整）移至你的位置，或失去 1 點影響力。',
    is_starter: false,
  },
  {
    id: 'VE07',
    name_en: 'Forestall',
    name_zh: '先發制人',
    clan: 'ventrue',
    type: 'passive',
    power: 3,
    effect_en: 'Immediately after Revelation, choose 1 Deployed card at a Rival\'s Position. You are immune to any Lose blood or Steal blood effect on that card and you Gain blood equal to its printed Power value.',
    effect_zh: '揭牌後立即，選擇對手位置上的 1 張部署牌。你免疫該牌的任何失去血液或偷取血液效果，並獲得等同其印刷權力值的血液。',
    is_starter: false,
  },
];

// ─── 起始牌 / 非起始牌分組 ──────────────────

export const CLAN_STARTERS: Record<ClanId, CardDef[]> = {
  brujah:   BRUJAH_CARDS.filter(c => c.is_starter),
  nosferatu: NOSFERATU_CARDS.filter(c => c.is_starter),
  toreador: TOREADOR_CARDS.filter(c => c.is_starter),
  tremere:  TREMERE_CARDS.filter(c => c.is_starter),
  malkavian: MALKAVIAN_CARDS.filter(c => c.is_starter),
  gangrel:  GANGREL_CARDS.filter(c => c.is_starter),
  ventrue:  VENTRUE_CARDS.filter(c => c.is_starter),
};

export const CLAN_DECKS: Record<ClanId, CardDef[]> = {
  brujah:   BRUJAH_CARDS.filter(c => !c.is_starter),
  nosferatu: NOSFERATU_CARDS.filter(c => !c.is_starter),
  toreador: TOREADOR_CARDS.filter(c => !c.is_starter),
  tremere:  TREMERE_CARDS.filter(c => !c.is_starter),
  malkavian: MALKAVIAN_CARDS.filter(c => !c.is_starter),
  gangrel:  GANGREL_CARDS.filter(c => !c.is_starter),
  ventrue:  VENTRUE_CARDS.filter(c => !c.is_starter),
};

// ─── 所有氏族牌（查詢用）────────────────────

const ALL_CLAN_CARDS: CardDef[] = [
  ...BRUJAH_CARDS,
  ...NOSFERATU_CARDS,
  ...TOREADOR_CARDS,
  ...TREMERE_CARDS,
  ...MALKAVIAN_CARDS,
  ...GANGREL_CARDS,
  ...VENTRUE_CARDS,
];

// ─── 盟友牌池 ────────────────────────────────

export const ALLY_POOL: AllyCard[] = [
  // ── Human ──────────────────────────────────────────────────────
  // drainBlood = blood_pool (one-time on drain), feedBlood = feed_blood (per round from bank)
  { id: 'AL19', name: 'Betty Fuller',        type: 'human',   influence: 3, feedBlood: 1, drainBlood: 3,  drainInfluence: 1, effect_zh: null },
  { id: 'AL22', name: 'Douglas Richardson', type: 'human',   influence: 2, feedBlood: 0, drainBlood: 8,  drainInfluence: 0, effect_zh: null },
  { id: 'AL30', name: 'Miguel Chandler',    type: 'human',   influence: 3, feedBlood: 2, drainBlood: 3,  drainInfluence: 0, effect_zh: '若你陷入狂怒，直接汲取此盟友，無需隨機抽取。' },
  { id: 'AL25', name: 'Elena Cortez',       type: 'human',   influence: 3, feedBlood: 3, drainBlood: 0,  drainInfluence: 0, effect_zh: null },
  { id: 'AL16', name: 'Bobby White',        type: 'human',   influence: 2, feedBlood: 0, drainBlood: 1,  drainInfluence: 3, effect_zh: null },
  { id: 'AL27', name: 'Roberta Urbani',     type: 'human',   influence: 3, feedBlood: 1, drainBlood: 3,  drainInfluence: 0, effect_zh: '在手牌建造階段，你可以保留兩張牌，並棄掉 1 張原本在手中的牌。' },
  { id: 'AL29', name: 'Sarah McAleer',      type: 'human',   influence: 3, feedBlood: 1, drainBlood: 2,  drainInfluence: 0, effect_zh: '獲得此盟友時，每擁有 1 張盟友或受害者，獲得 1 點血液。' },
  { id: 'AL24', name: 'Francis Bennet',     type: 'human',   influence: 3, feedBlood: 1, drainBlood: 5,  drainInfluence: 1, effect_zh: null },
  { id: 'AL21', name: 'Tamara Bodnar',      type: 'human',   influence: 5, feedBlood: 3, drainBlood: 1,  drainInfluence: 0, effect_zh: null },
  { id: 'AL26', name: 'Julie Munoz',        type: 'human',   influence: 3, feedBlood: 1, drainBlood: 3,  drainInfluence: 0, effect_zh: '若遊戲結束時此牌是你唯一的人類盟友，你獲得 +2 影響力。' },
  { id: 'AL1G', name: 'Ed Crawford',        type: 'human',   influence: 3, feedBlood: 2, drainBlood: 2,  drainInfluence: 0, effect_zh: null },
  { id: 'AL20', name: 'Dr. Fragonard',      type: 'human',   influence: 4, feedBlood: 2, drainBlood: 2,  drainInfluence: 1, effect_zh: null },
  { id: 'AL28', name: 'Ryan Ramos',         type: 'human',   influence: 4, feedBlood: 1, drainBlood: 3,  drainInfluence: 4, effect_zh: '每當你打出面朝下的牌時，你必須額外消耗 +1 血液。' },
  { id: 'AL17', name: 'Maja Wysocki',       type: 'human',   influence: 3, feedBlood: 1, drainBlood: 1,  drainInfluence: 2, effect_zh: null },
  { id: 'AL23', name: 'Tom Kimber',         type: 'human',   influence: 4, feedBlood: 2, drainBlood: 2,  drainInfluence: 0, effect_zh: null },
  // ── Vampire ────────────────────────────────────────────────────
  { id: 'AL04', name: 'Wauneka',            type: 'vampire', influence: 3, feedBlood: 1, drainBlood: 3,  drainInfluence: 0, effect_zh: '獲得此盟友時，從牌堆抽取 1 張受害者牌並加入你的同盟區。' },
  { id: 'AL15', name: 'Mr. Damp',           type: 'vampire', influence: 3, feedBlood: 1, drainBlood: 3,  drainInfluence: 0, effect_zh: '當你迫使對手陷入狂怒時，獲得 2 點血液。' },
  { id: 'AL11', name: 'Portia',             type: 'vampire', influence: 5, feedBlood: 0, drainBlood: 0,  drainInfluence: 0, effect_zh: '此盟友無法被汲取（若你陷入狂怒，將此牌留在你的同盟區）。' },
  { id: 'AL09', name: 'Marcel',             type: 'vampire', influence: 4, feedBlood: 2, drainBlood: 4,  drainInfluence: 1, effect_zh: null },
  { id: 'AL07', name: 'Erichtho',           type: 'vampire', influence: 3, feedBlood: 1, drainBlood: 3,  drainInfluence: 0, effect_zh: '每當你打出面朝下的牌時，少消耗 1 點血液。' },
  { id: 'AL13', name: 'Ambrus Maropis',     type: 'vampire', influence: 3, feedBlood: 1, drainBlood: 3,  drainInfluence: 0, effect_zh: '你可以消耗血液查看任意面朝下的牌：每消耗 1 點血液查看 1 張。' },
  { id: 'AL03', name: 'Khadija Al-Kindi',   type: 'vampire', influence: 3, feedBlood: 1, drainBlood: 3,  drainInfluence: 0, effect_zh: '獲得此盟友時，從你的牌堆抽取 1 張氏族牌並加入手牌。' },
  { id: 'AL08', name: 'Fiorenza Savona',    type: 'vampire', influence: 3, feedBlood: 1, drainBlood: 3,  drainInfluence: 0, effect_zh: '你在所有平局中獲勝。' },
  { id: 'AL05', name: 'Carmelita Neillson', type: 'vampire', influence: 3, feedBlood: 1, drainBlood: 3,  drainInfluence: 0, effect_zh: '每當你在王子的避難所打出牌時，從銀行取 1 點血液放置於該地點。' },
  { id: 'AL06', name: 'Maldavis',           type: 'vampire', influence: 3, feedBlood: 1, drainBlood: 3,  drainInfluence: 0, effect_zh: '獲得此盟友時，獲得 5 點血液。' },
  { id: 'AL14', name: 'Edward Neally',      type: 'vampire', influence: 5, feedBlood: 3, drainBlood: 3,  drainInfluence: 0, effect_zh: '若你汲取此盟友，獲得 2 個弒祖標記而非 1 個。' },
  { id: 'AL02', name: 'Sgt. McTavish',      type: 'vampire', influence: 3, feedBlood: 1, drainBlood: 3,  drainInfluence: 0, effect_zh: '獲得此盟友時，從每位對手竊取 2 點血液。' },
  { id: 'AL01', name: 'Anita Wainwright',   type: 'vampire', influence: 3, feedBlood: 1, drainBlood: 3,  drainInfluence: 0, effect_zh: '獲得此盟友時，獲得 3 點血液。' },
  { id: 'AL12', name: 'Talley',             type: 'vampire', influence: 2, feedBlood: 0, drainBlood: 3,  drainInfluence: 0, effect_zh: '當你迫使對手陷入狂怒時，額外獲得 +1 影響力。' },
  { id: 'AL10', name: 'Bronwyn',            type: 'vampire', influence: 5, feedBlood: 1, drainBlood: 3,  drainInfluence: 1, effect_zh: null },
];

// ─── 受害者牌池 ──────────────────────────────

export const VICTIM_POOL: AllyCard[] = Array.from({ length: 12 }, (_, i) => ({
  id: `v${i + 1}`,
  name: `Kine #${i + 1}`,
  type: 'human' as const,
  influence: 1,
  feedBlood: 1,
  drainBlood: 2,
  drainInfluence: 0,
}));

// ─── 輔助函式 ────────────────────────────────

export function getCardById(id: string): CardDef | undefined {
  return ALL_CLAN_CARDS.find(c => c.id === id);
}

export function getCardImage(cardId: string, clan: ClanId | 'neutral'): string {
  if (clan === 'neutral') return '';
  const num = cardId.slice(-2);
  return `/assets/${clan}/card_${num}.png`;
}

export function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function getClanColor(clan: ClanId): string {
  return CLAN_DEFS[clan].color;
}
